INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('User', 'UserRole', 1, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Trainer', 'UserRole', 2, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Subject Manager', 'UserRole', 3, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Administrator', 'UserRole', 4, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('SPRING 2021', 'Semester', 5, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('SUMMER 2021', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('FALL 2021', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('SPRING 2022', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('SUMMER 2022', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('FALL 2022', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('SPRING 2023', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('SUMMER 2023', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('FALL 2023', 'Semester', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Skill', 'Dimension Type', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Technical', 'Dimension Type', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Video', 'Lesson Type', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Quiz', 'Lesson Type', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Assignment', 'Lesson Type', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Chapter', 'Subject Setting', NULL, 1);
INSERT INTO system_setting (setting_name, setting_type, display_order, setting_status) VALUES ('Dimension', 'Subject Setting', NULL, 1);

INSERT INTO account (username, email, password, role, status, full_name, mobile,  enrolment_date) VALUES ('bangthhe170871', 'bangthhe170871@fpt.edu.vn', '1', 3, 1, 'Tran Hai Bang', '0394672294', '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile, enrolment_date) VALUES ('trungnqhe172809', 'trungnqhe172809@fpt.edu.vn', '1', 4, 1, 'Nguyen Quoc Trung', '0394672295',  '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile, enrolment_date) VALUES ('quannahe170031', 'quannahe170031@fpt.edu.vn', '1', 3, 1, 'Nguyen Anh Quan', '0394672296',  '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,  enrolment_date) VALUES ('banthhe170872', 'banthhe170872@fpt.edu.vn', '1', 3, 1, 'Tran Hai Ban', '0394672297', '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile, enrolment_date) VALUES ('bathhe170873', 'bathhe170873@fpt.edu.vn', '1', 3, 1, 'Tran Hai Ba', '0394672298',  '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,   enrolment_date) VALUES ('binhthhe170874', 'binhthhe170874@fpt.edu.vn', '1', 3, 1, 'Tran Hai Binh', '0394672299', '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,   enrolment_date) VALUES ('baothhe170875', 'baothhe170875@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672214', '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,  enrolment_date) VALUES ('baothhe170876', 'baothhe170876@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672224',  '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,   enrolment_date) VALUES ('baothhe170877', 'baothhe170877@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672234',  '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,   enrolment_date) VALUES ('baothhe170878', 'baothhe170878@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672244', '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,  enrolment_date) VALUES ('baothhe170879', 'baothhe170879@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672254','2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,   enrolment_date) VALUES ('baothhe170870', 'baothhe170870@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672264', '2021-04-20');
INSERT INTO account (username, email, password, role, status, full_name, mobile,   enrolment_date) VALUES ('baothhe170885', 'baothhe170885@fpt.edu.vn', '1', 1, 1, 'Tran Hai Bao', '0394672274',  '2021-04-20');

INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('SWP391', 'Application Software Development', NULL, 1, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('PRN211', 'Basic Crossform Application with C#', NULL, 4, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('SWR302', 'Software Requirement', NULL, 3, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('SWT301', 'Software Testing', NULL, 5, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('SWP491', 'Capstone Project', NULL, 6, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('DBI202', 'Database Introduction', NULL, 1, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('PRF192', 'Programming Fundamentals', NULL, 1, 1);
INSERT INTO subject (subject_code, subject_name, subject_des, manager, status) VALUES ('OJT202', 'On The Job Training', NULL, 1, 1);

INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1730', 1, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1730', 2, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1730', 3, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1730', 4, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1730', 5, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1730', 6, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1731', 1, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO class (class_name, subject_id, semester, status, start_date, end_date, start_time, end_time) VALUES ('SE1731', 2, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');

INSERT INTO student_class VALUES (8, 7, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (8, 1, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (9, 1, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (10, 1, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (11, 1, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (8, 2, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (11, 2, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (8, 3, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');
INSERT INTO student_class VALUES (9, 3, 13, 1, '2023-05-09', '2023-12-01', '00:00:00.00', '23:59:00.00');

INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 1: Introduction', 1, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 1: Planning', 2, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 1: DB Design', 3, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 1: Code', 4, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 1: Summary', 5, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 2: Introduction', 6, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 2: Planning', 7, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 2: DB Design', 8, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 2: Code', 9, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 2: Summary', 10, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 3: Introduction', 11, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 3: Planning', 12, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 3: DB Design', 13, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 3: Code', 14, 'Chapter', 1, '2021-04-20', 1);
INSERT INTO subject_setting (subject_id, setting_name, display_order, setting_type, created_by, created_at, status) VALUES (1, 'Iteration 3: Summary', 15, 'Chapter', 1, '2021-04-20', 1);

INSERT INTO dimension_type (type_name, status) VALUES ('Skill', 1);
INSERT INTO dimension_type (type_name, status) VALUES ('Group', 1);

INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (1, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (1, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (1, 'Introduction about Iteration 1 & Explanning', 17, 3, NULL, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (2, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (2, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/U5IpIMm-Hks?si=QinGfAzNuq662NSu', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (2, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/U5IpIMm-Hks?si=QinGfAzNuq662NSu', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (3, 'Introduction about Iteration 1 & Explanning', 18, 1, NULL, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (3, 'Introduction about Iteration 1 & Explanning', 17, 2, NULL, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (3, 'Introduction about Iteration 1 & Explanning', 18, 3, NULL, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (4, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (4, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (4, 'Introduction about Iteration 1 & Explanning', 17, 3, NULL, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (5, 'Introduction about Iteration 1 & Explanning', 18, 1, NULL, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (5, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (5, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (6, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (6, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (6, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (6, 'Introduction about Iteration 1 & Explanning', 16, 4,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (7, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (7, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (8, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (8, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (8, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (9, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (9, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (9, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (10, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (10, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (10, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 4,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 5,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 6,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (11, 'Introduction about Iteration 1 & Explanning', 16, 7,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (12, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (12, 'Introduction about Iteration 1 & Explanning', 16, 2,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (12, 'Introduction about Iteration 1 & Explanning', 16, 3,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (12, 'Introduction about Iteration 1 & Explanning', 16, 4,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO lesson (chapter_id, lesson_name, lesson_type, display_order, video_link, created_by, created_at, status) VALUES (13, 'Introduction about Iteration 1 & Explanning', 16, 1,'https://www.youtube.com/embed/DgGtpCp7aQk?si=2mXgeb4TvgExPcuz', 1, '2023-04-20 00:00:00.00', 1);

UPDATE lesson SET description = 'About this subject, based on a specific topic, you need to build a corresponding software product. The progress will be divided into 3 parts: Iteration 1, Iteration 2 and Iteration 3. On each iteration, you will need to complete a specific amount of tasks to pass this subject. This video simply wants to introduce and explain to you more clearly about Iteration 1: what you guys must do in this process and how to do it. Moreover, this may give you many suggestions about what you guys want to do in Iteration 2 and Iteration 3. We hope that you will find this video in particular and the lesson in general interesting, challenging, so that you will have a good experience to prepare for OJT. And the last thing, we want to thank you all for choosing to study this subject and we wish for you all the best things in the world.';
INSERT INTO quiz (quiz_name, chapter_id, subject_id, noQ, time_limit, display_order, created_by, created_at, status) VALUES ('Iteration 1 Quiz', 1, 1, 10, 90, 1, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO quiz (quiz_name, chapter_id, subject_id, noQ, time_limit, display_order, created_by, created_at, status) VALUES ('Iteration 2 Quiz', 3, 1, 10, 90, 1, 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO quiz (quiz_name, chapter_id, subject_id, noQ, time_limit, display_order, created_by, created_at, status) VALUES ('Iteration 3 Quiz', 4, 1, 10, NULL, 1, 1, '2023-04-20 00:00:00.00', 1);
UPDATE quiz SET description = 'About this subject, based on a specific topic, you need to build a corresponding software product. The progress will be divided into 3 parts: Iteration 1, Iteration 2 and Iteration 3. On each iteration, you will need to complete a specific amount of tasks to pass this subject. This video simply wants to introduce and explain to you more clearly about Iteration 1: what you guys must do in this process and how to do it. Moreover, this may give you many suggestions about what you guys want to do in Iteration 2 and Iteration 3. We hope that you will find this video in particular and the lesson in general interesting, challenging, so that you will have a good experience to prepare for OJT. And the last thing, we want to thank you all for choosing to study this subject and we wish for you all the best things in the world.';

INSERT INTO assignment (asm_name, class_id, subject_id, chapter_id, lesson_id, deadline, created_by, created_at, status) VALUES ('Project Submit', 1, 1, 3, 7, '2023-11-20', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO assignment (asm_name, class_id, subject_id, chapter_id, lesson_id, deadline, created_by, created_at, status) VALUES ('Project Submit', 1, 1, 3, 9, '2023-11-20', 1, '2023-04-20 00:00:00.00', 1);
INSERT INTO assignment (asm_name, class_id, subject_id, chapter_id, lesson_id, deadline, created_by, created_at, status) VALUES ('Project Submit', 1, 1, 5, 13, '2023-11-20', 1, '2023-04-20 00:00:00.00', 1);

INSERT INTO grade_item (item_name, student_id, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Iteration 1 Quiz', 8, 1, 4.5, NULL, '2023-10-20 00:00:00.00', 45, 1, NULL);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Iteration 1 Quiz', 8, 'Quiz', 2, 6, NULL, '2023-10-20 00:00:00.00', 45, 1, NULL);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Iteration 1 Quiz', 8, 'Quiz', 3, 10, NULL, '2023-10-20 00:00:00.00', 45, 1, NULL);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Iteration 2 Quiz', 8, 'Quiz', 1, 9.5, NULL, '2023-10-20 00:00:00.00', 45, 2, NULL);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Iteration 2 Quiz', 8, 'Quiz', 2, 9.5, NULL, '2023-10-20 00:00:00.00', 45, 2, NULL);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Iteration 3 Quiz', 8, 'Quiz', 1, 10, NULL, '2023-10-20 00:00:00.00', 45, 1, NULL);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Project Submit', 8, 'Assignment', 1, 4.5, NULL, '2023-10-20 00:00:00.00', 45, NULL, 1);
INSERT INTO grade_item (item_name, student_id, item_type, count, grade, notes, date_taken, time_taken, quiz_id, asm_id) VALUES ('Project Submit', 8, 'Assignment', 1, 4.5, NULL, '2023-10-20 00:00:00.00', 45, NULL, 2);
UPDATE grade_item SET item_type = 'Quiz' WHERE item_id = 1;
UPDATE grade_item SET time_taken = NULL where item_type = 'Assignment';
UPDATE grade_item SET notes = 'Chỉ làm phần 2 và 3, không đạt, cần chỉnh sửa thêm' WHERE item_ID = 7;
UPDATE grade_item SET notes = 'Đạt' WHERE item_ID = 8;
UPDATE grade_item SET class_id = 1;

INSERT INTO class_discussion (account_id, class_id, discussion_topic, discussion_content, discussion_date, status) VALUES (8, 1, 'How to become good at programming ?', 'I have just entered college to study software engineering but I find it so hard to study. Can anybody that has got over this problem tell me how to deal with this situation right now ?', '2023-07-20 00:00:00.00', 1);
INSERT INTO class_discussion (account_id, class_id, discussion_topic, discussion_content, discussion_date, status) VALUES (9, 1, 'How to become good at math ?', 'I have just entered college to study software engineering but I find it so hard to study. I think this is because I study math so badly, and in future, I have to study a lot more about math if I want to become a software engineer. So can anyone tell me how to get better at math ?', '2023-07-21 00:00:00.00', 1);
INSERT INTO class_discussion (account_id, class_id, discussion_topic, discussion_content, discussion_date, status) VALUES (10, 1, 'Youtube channels that you find most interesting about programming ?', 'I have just entered college to study software engineering but I find it so hard to study and I hear a lot of people say one way to get better at this is to self-study. I have gone to Youtube and searched for many channels so that I can learn new things but I don’t find any that match my interest. Can you gúy suggest some to me ?', '2023-07-22 00:00:00.00', 1);
INSERT INTO class_discussion (account_id, class_id, discussion_topic, discussion_content, discussion_date, status) VALUES (11, 1, 'Ways to increase confidence ?', 'I am a self-deprecated person and I found it very bad. I want to become more confident but I can’t figure how. Can anybody tell me ?', '2023-07-22 00:00:00.00', 1);
UPDATE class_discussion SET noVote = 22;
UPDATE account SET password = 'c4ca4238a0b923820dcc509a6f75849b'
